// Code generated by "/pkgs/automapper"; DO NOT EDIT.
package mapper

import (
	"github.com/hay-kot/git-web-template/backend/ent"
	"github.com/hay-kot/git-web-template/backend/internal/dtos"
)

func UserOutFromModel(from ent.User) dtos.UserOut {
	return dtos.UserOut{
		Id:          from.ID,
		Name:        from.Name,
		Email:       from.Email,
		Password:    from.Password,
		IsSuperuser: from.IsSuperuser,
	}
}

func UserOutToModel(from dtos.UserOut) ent.User {
	return ent.User{
		ID:          from.Id,
		Name:        from.Name,
		Email:       from.Email,
		Password:    from.Password,
		IsSuperuser: from.IsSuperuser,
	}
}
