name: Go Build/Test

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "client/**/*.ts"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "client/**/*.ts"

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build API
        run: task api:build

      - name: Build CLI
        run: task cli:build
      - name: Test
        run: task api:coverage

      - name: Upload coverage to Codecov
        run: cd backend && bash <(curl -s https://codecov.io/bash)
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build API
        run: task api:build

      - name: Setup Node
        working-directory: ./client
        run: npm install

      - name: Test
        run: task client:test
