name: Go Build/Test

on:
  push:
    branches: [master]
    paths:
      - "**.go"
      - "client/**/*.ts"
  pull_request:
    branches: [master]
    paths:
      - "**.go"
      - "client/**/*.ts"

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build API
        run: make build

      - name: Build CLI
        run: make cli

      - name: Test
        run: make coverage

      - name: Upload coverage to Codecov
        run: cd backend && bash <(curl -s https://codecov.io/bash)
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build API
        run: make build

      - name: Setup Node
        working-directory: ./client
        run: npm install

      - name: Test
        run: make test-client
