name: Go Build/Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build API
        run: make build

      - name: Build CLI
        run: make cli

      - name: Test
        run: make coverage

      - name: Upload coverage to Codecov
        run: cd backend && bash <(curl -s https://codecov.io/bash)
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Node
        uses: actions/setup-node@v2
        working-directory: ./client
        run: npm install

      - name: Test
        run: make end-to-end-test
