name: Build Docker Image

on:
  release:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: login to container registry
        run: echo $CR_PAT | docker login ghcr.io - USERNAME --password-stdin
      - name: Build Docker Image
        run: cd backend && docker build -t ghcr.io/hay-kot/go-web-template:latest .
      - name: push to container registry
        run: docker push ghcr.io/hay-kot/go-web-template:latest
